# This is a -*- Makefile -*-

CFLAGS += -DDTLSv12 -DWITH_SHA256 -DCONTIKI -DSHA2_USE_INTTYPES_H=1 -DDTLS_CONF_PSK=1 -DDTLS_CONF_ECC=0
tinydtls_src = dtls.c dtls_crypto.c hmac.c rijndael.c sha2.c dtls_ccm.c netq.c dtls_time.c peer.c session.c

# This activates debugging support
#CFLAGS += -DNDEBUG
tinydtls_src += dtls_debug.c